#!/bin/bash
echo Compiling kernel...
if /mnt/d/cross/bin/i686-elf-g++ -c src/core/kernel2.cpp -o obj/kernel.o -ffreestanding -O2 -Wall -Wextra -fno-exceptions -fno-rtti; then
	echo Linking and generation OS file...
	/mnt/d/cross/bin/i686-elf-g++ -T src/core/linker.ld -o bin/myos.bin -ffreestanding -O2 -nostdlib obj/boot.o obj/kernel.o -lgcc
	sh scripts/checkos
else
	echo error during kernel compilation exiting...
	exit 1
fi
exit 0