#!/bin/bash
echo Compiling kernel...
bash scripts/compilecpp
if [ $? = 0 ]; then
	echo Linking and generation OS file...
	oFiles=`find -name \*.o`
	/mnt/d/cross/bin/i686-elf-g++ -T src/core/linker.ld -o bin/myos.bin -ffreestanding -O2 -nostdlib $oFiles -lgcc -Xlinker -zmuldefs
	sh scripts/checkos
else
	echo error during kernel compilation exiting...
	exit 1
fi
exit 0