#!/bin/bash
echo Compiling cpp files...
cppFiles=`find -name \*.cpp`
/mnt/d/cross/bin/i686-elf-g++ -c $cppFiles -ffreestanding -O2 -Wall -Wextra -fno-exceptions -fno-rtti;
for file in $cppFiles
do
	echo "Compiling file: $file"
	oFile=${file/.cpp/.o}
	oFile=${oFile##*/}
	mv $oFile ./obj
done
#Old cmd
#/mnt/d/cross/bin/i686-elf-g++ -c src/core/kernel2.cpp -o obj/kernel.o -ffreestanding -O2 -Wall -Wextra -fno-exceptions -fno-rtti;
exit 0